In [123]:
from statistics import median


def load_dataset(filename):
    import csv
    rows = []
    with open(filename, 'r' , encoding='utf-8') as file:
        reader = csv.DictReader(file)
        for row in reader:
            rows.append(row)

    return rows

In [124]:
numerical_columns = [
    'Tenure',
    'WarehouseToHome',
    'NumberOfDeviceRegistered',
    'SatisfactionScore',
    'NumberOfAddress',
    'Complain',
    'DaySinceLastOrder',
    'CashbackAmount'
]

In [125]:
import numpy as np

In [126]:
def transaction_clean(transactions):
    clean_transactions = []
    for row in transactions:
        valid = True
        for column in row:
            if row[column].strip() == "":
                valid = False
                break
        if valid:
            clean_transactions.append(row)
    return clean_transactions

In [127]:
transactions = load_dataset('data/data_ecommerce_customer_churn.csv')
clean_transactions = transaction_clean(transactions)

In [128]:
X = np.array([
    [float(row[column]) for column in numerical_columns]
    for row in clean_transactions
])
print("X shape:", X.shape)
print("X ndim:", X.ndim)
print("X size:", X.size)
print("X dtype:", X.dtype)

X shape: (3365, 8)
X ndim: 2
X size: 26920
X dtype: float64


In [129]:
y = np.array([
    int(row["Churn"])
    for row in clean_transactions
])

print("y shape:", y.shape)
print("y ndim:", y.ndim)
print("y size:", y.size)
print("y dtype:", y.dtype)


y shape: (3365,)
y ndim: 1
y size: 3365
y dtype: int64


In [130]:
print("First customer: " , X[0])
print("First 5 customers: ", X[0:5])
print("First 3 features of first customer: ", X[0,:3])
print("Last 5 customers: ",X[-5:])
print("Entire Tenure column: " , X[:,0])
print("First customer's Tenure: ", X[0,0])
print("First customer's SatisfactionScore: ", X[0,3])


First customer:  [ 15.    29.     4.     3.     2.     0.     7.   143.32]
First 5 customers:  [[ 15.    29.     4.     3.     2.     0.     7.   143.32]
 [  7.    25.     4.     1.     2.     0.     7.   129.29]
 [ 27.    13.     3.     1.     5.     0.     7.   168.54]
 [ 30.    15.     4.     4.     8.     0.     8.   322.17]
 [  7.    16.     4.     2.     2.     0.    11.   152.81]]
First 3 features of first customer:  [15. 29.  4.]
Last 5 customers:  [[ 26.     7.     4.     1.     4.     0.     9.   295.99]
 [ 28.     9.     5.     3.     8.     0.     1.   231.86]
 [  8.     7.     2.     2.     4.     0.     4.   157.8 ]
 [ 30.     6.     5.     3.     3.     1.     2.   156.6 ]
 [  2.     7.     3.     5.     1.     0.     2.   153.73]]
Entire Tenure column:  [15.  7. 27. ...  8. 30.  2.]
First customer's Tenure:  15.0
First customer's SatisfactionScore:  3.0


In [131]:
tenure = X[:,0]
print("tenure mean: ",np.mean(tenure))
print("tenure Median: ",np.median(tenure))
print("tenure Minimum: ",np.min(tenure))
print("tenure Maximum: ",np.max(tenure))
print("tenure Standard deviation: ",np.std(tenure))



tenure mean:  10.177711738484398
tenure Median:  9.0
tenure Minimum:  0.0
tenure Maximum:  61.0
tenure Standard deviation:  8.51167764189064


In [132]:
print("Mean: ", np.mean(X , axis = 0) )
print("Median: ", np.median(X , axis = 0))
print("Minimum: ", np.min(X , axis = 0))
print("Maximum: ", np.max(X , axis = 0))
print("Standard deviation: ", np.std(X , axis = 0))

Mean:  [ 10.17771174  15.71381872   3.69895988   3.09420505   4.29658247
   0.28350669   4.78008915 179.77472511]
Median:  [  9.    14.     4.     3.     3.     0.     4.   165.14]
Minimum:  [0. 5. 1. 1. 1. 0. 0. 0.]
Maximum:  [ 61.   127.     6.     5.    22.     1.    46.   324.99]
Standard deviation:  [ 8.51167764  8.51244011  1.02394023  1.38095053  2.6258522   0.45070017
  3.68528926 48.28629583]


In [133]:
print(X[:,0] > 10)

[ True False  True ... False  True False]


In [134]:
print(X[:,3]<=2)

[False  True  True ...  True False False]


In [135]:
print(X[:,7]>300)

[False False False ... False False False]


In [136]:
print(X[:,6]>10)


[False False False ... False False False]


In [137]:
mask1 = (X[:, 3] <= 2 ) & (X[:, 5] == 1)

In [138]:
low_satisfaction_flag = np.where(X[:,7] <= 2 , 1, 0)

In [139]:
inactive_flag = np.where(X[:,6]>10,1,0)

In [140]:
complaint_flag = np.where(X[:,5]==1 , 1 , 0)

In [141]:
Tenure = X[:,0]
NumberOfDeviceRegistered = X[:,2]
NumberOfAddress = X[:,4]
DaySinceLastOrder = X[:,6]

Engagement_Score = Tenure + NumberOfDeviceRegistered + NumberOfAddress - DaySinceLastOrder
print(Engagement_Score)

[14.  6. 28. ... 10. 36.  4.]


In [142]:
print("mean: ",np.mean(Engagement_Score))
print("median: ",np.median(Engagement_Score))
print("min: ",np.min(Engagement_Score))
print("standard deviation: ",np.std(Engagement_Score))

mean:  13.393164933135216
median:  11.0
min:  -36.0
standard deviation:  9.749535635582774


In [143]:
cashback = X[:,7]
tenure = X[:,0]
print(np.where(tenure == 0 ,"tenure is 0",cashback/tenure ))



['9.554666666666666' '18.47' '6.242222222222222' ... '19.725' '5.22'
 '76.865']


C:\Users\Aayus\AppData\Local\Temp\ipykernel_24388\561058111.py:3: RuntimeWarning: divide by zero encountered in divide
  print(np.where(tenure == 0 ,"tenure is 0",cashback/tenure ))


In [144]:
feature_means = np.mean(X,axis = 0)
feature_std = np.std(X,axis = 0)

X_scaled = (X-feature_means)/feature_std

print("Original shape:", X.shape)
print("Scaled shape:", X_scaled.shape)

print("\nScaled means:")
print(np.mean(X_scaled, axis=0))

print("\nScaled standard deviations:")
print(np.std(X_scaled, axis=0))

Original shape: (3365, 8)
Scaled shape: (3365, 8)

Scaled means:
[ 1.48205701e-16  1.71696898e-16 -2.22968416e-16 -1.34678466e-16
 -1.45830186e-17 -3.13435921e-17  5.48347895e-17  1.10548849e-14]

Scaled standard deviations:
[1. 1. 1. 1. 1. 1. 1. 1.]


In [145]:
churned_mask = y == 1

churned_customers = np.sum(churned_mask)

print("Churned customers:", churned_customers)

Churned customers: 510


In [146]:
non_churned_mask = y == 0
non_churned_customers = np.sum(non_churned_mask)
print("Non Churned Customers = " , non_churned_customers)

Non Churned Customers =  2855


In [147]:
print(churned_customers + non_churned_customers)
print(total_customers)

3365
3365


In [148]:
churn_rate = np.mean(y == 1)
churned_features = X[y == 1]
non_churned_features = X[y == 0]

churned_means = np.mean(churned_features, axis=0)
non_churned_means = np.mean(non_churned_features, axis=0)

difference = churned_means - non_churned_means
print("Churn rate:", churn_rate)
print("Churn rate (%):", churn_rate * 100)

Churn rate: 0.1515601783060921
Churn rate (%): 15.156017830609212


In [149]:
print("===== CHURN SUMMARY =====")
print("Total customers:", total_customers)
print("Churned:", churned_customers)
print("Non-churned:", non_churned_customers)
print("Churn rate:", round(churn_rate * 100, 2), "%")

===== CHURN SUMMARY =====
Total customers: 3365
Churned: 510
Non-churned: 2855
Churn rate: 15.16 %


In [150]:
low_satisfaction = X[:, 3] <= 2
has_complaint = X[:, 5] == 1
inactive = X[:, 6] > 10
low_tenure = X[:, 0] < 5
few_addresses = X[:, 4] <= 1

risk_score = (
    np.where(low_satisfaction,2,0)+
    np.where(has_complaint,2,0)+
    np.where(inactive,2,0)+
    np.where(low_tenure,1,0)+
    np.where(few_addresses,1,0)
)

print("Minimum risk:", np.min(risk_score))
print("Maximum risk:", np.max(risk_score))

print("\nFirst 20 risk scores:")
print(risk_score[:20])

Minimum risk: 0
Maximum risk: 6

First 20 risk scores:
[0 2 2 0 4 1 1 0 4 0 1 0 0 2 6 1 1 1 2 2]


In [151]:
risk_group = np.where(
    risk_score <=2 , "Low",
    np.where(risk_score <= 4 , "Medium",
             "High"
             )
)
print(risk_group[:20])

print()
print(np.unique(risk_group,return_counts=True))

['Low' 'Low' 'Low' 'Low' 'Medium' 'Low' 'Low' 'Low' 'Medium' 'Low' 'Low'
 'Low' 'Low' 'Low' 'High' 'Low' 'Low' 'Low' 'Low' 'Low']

(array(['High', 'Low', 'Medium'], dtype='<U6'), array([ 154, 2478,  733]))


In [152]:
low_risk = risk_group == "Low"
low_risk_total  = np.sum(low_risk)
low_risk_churned = np.sum(y[low_risk] == 1)

low_churn_rate = low_risk_churned / low_risk_total
print("Low Risk")
print("Customers:", low_risk_total)
print("Churned:", low_risk_churned)
print("Churn rate:", low_churn_rate * 100, "%")

Low Risk
Customers: 2478
Churned: 252
Churn rate: 10.16949152542373 %


In [153]:
medium_risk = risk_group == "Medium"

medium_risk_total = np.sum(medium_risk)
medium_risk_churn = np.sum(y[medium_risk] == 1)
medium_churn_rate = medium_risk_churn/medium_risk_total

print("Medium Risk")
print("Customers:", medium_risk_total)
print("Churned:", medium_risk_churn)
print("Churn rate:", medium_churn_rate * 100, "%")

Medium Risk
Customers: 733
Churned: 194
Churn rate: 26.46657571623465 %


In [154]:
high_risk = risk_group == "High"
high_risk_total = np.sum(high_risk)
high_risk_churn = np.sum(y[high_risk] == 1)

high_churn_rate = high_risk_churn/high_risk_total

print("High Risk")
print("Customers:", high_risk_total)
print("Churned:", high_risk_churn)
print("Churn rate:", high_churn_rate * 100, "%")

High Risk
Customers: 154
Churned: 64
Churn rate: 41.55844155844156 %


In [155]:
import numpy as np
import time

values = np.random.random(1_000_000)

start = time.time()

result_loop = []

for x in values:
    result_loop.append(x**2 + 2*x + 5)

loop_time = time.time() - start

print("Python loop time:", loop_time)

start = time.time()

result_numpy = values**2 + 2*values + 5

numpy_time = time.time() - start

print("NumPy time:", numpy_time)

speedup = loop_time / numpy_time

print("Python loop:", loop_time)
print("NumPy:", numpy_time)
print("Speedup:", speedup, "x")

Python loop time: 0.5966215133666992
NumPy time: 0.012801170349121094
Python loop: 0.5966215133666992
NumPy: 0.012801170349121094
Speedup: 46.60679430827684 x


In [156]:
print("=" * 60)
print("NUMPY CUSTOMER CHURN ANALYSIS")
print("=" * 60)

# Dataset
print("\nDATASET")
print("-" * 60)
print("Total customers analyzed:", len(X))
print("Rows removed:", len(transactions) - len(clean_transactions))
print("Numerical features:", len(numerical_columns))

# Churn
print("\nCHURN")
print("-" * 60)
print("Churned customers:", churned_customers)
print("Non-churned customers:", non_churned_customers)
print("Overall churn rate:", round(churn_rate * 100, 2), "%")

# Risk groups
print("\nRISK GROUP ANALYSIS")
print("-" * 60)

print(
    "Low    | Customers:", low_risk_total,
    "| Churned:", low_risk_churned,
    "| Churn rate:", round(low_churn_rate * 100, 2), "%"
)

print(
    "Medium | Customers:", medium_risk_total,
    "| Churned:", medium_risk_churn,
    "| Churn rate:", round(medium_churn_rate * 100, 2), "%"
)

print(
    "High   | Customers:", high_risk_total,
    "| Churned:", high_risk_churn,
    "| Churn rate:", round(high_churn_rate * 100, 2), "%"
)

# Engagement
print("\nENGAGEMENT SCORE")
print("-" * 60)
print("Mean:", round(np.mean(Engagement_Score), 2))
print("Minimum:", round(np.min(Engagement_Score), 2))
print("Maximum:", round(np.max(Engagement_Score), 2))
print("Standard deviation:", round(np.std(Engagement_Score), 2))

# Performance
print("\nPERFORMANCE")
print("-" * 60)
print("Python loop time:", loop_time)
print("NumPy time:", numpy_time)
print("Speedup:", round(speedup, 2), "x")

# Verification
print("\nVERIFICATION")
print("-" * 60)
print(
    "Loop and NumPy results equivalent:",
    np.allclose(result_loop, result_numpy)
)

NUMPY CUSTOMER CHURN ANALYSIS

DATASET
------------------------------------------------------------
Total customers analyzed: 3365
Rows removed: 576
Numerical features: 8

CHURN
------------------------------------------------------------
Churned customers: 510
Non-churned customers: 2855
Overall churn rate: 15.16 %

RISK GROUP ANALYSIS
------------------------------------------------------------
Low    | Customers: 2478 | Churned: 252 | Churn rate: 10.17 %
Medium | Customers: 733 | Churned: 194 | Churn rate: 26.47 %
High   | Customers: 154 | Churned: 64 | Churn rate: 41.56 %

ENGAGEMENT SCORE
------------------------------------------------------------
Mean: 13.39
Minimum: -36.0
Maximum: 70.0
Standard deviation: 9.75

PERFORMANCE
------------------------------------------------------------
Python loop time: 0.5966215133666992
NumPy time: 0.012801170349121094
Speedup: 46.61 x

VERIFICATION
------------------------------------------------------------
Loop and NumPy results equivalent: T