In [1]:
import csv
def load_dataset(filename):
    rows = []
    with open(filename, mode='r', encoding = "utf-8", newline= "") as file:
        reader = csv.DictReader(file)
        for row in reader:
            rows.append(row)

    return rows

In [2]:
transactions = load_dataset("./data/data_ecommerce_customer_churn.csv")

print("Number of rows:", len(transactions))
print("First row:")
print(transactions[0])

print("\nColumns:")
print(transactions[0].keys())

Number of rows: 3941
First row:
{'Tenure': '15.0', 'WarehouseToHome': '29.0', 'NumberOfDeviceRegistered': '4', 'PreferedOrderCat': 'Laptop & Accessory', 'SatisfactionScore': '3', 'MaritalStatus': 'Single', 'NumberOfAddress': '2', 'Complain': '0', 'DaySinceLastOrder': '7.0', 'CashbackAmount': '143.32', 'Churn': '0'}

Columns:
dict_keys(['Tenure', 'WarehouseToHome', 'NumberOfDeviceRegistered', 'PreferedOrderCat', 'SatisfactionScore', 'MaritalStatus', 'NumberOfAddress', 'Complain', 'DaySinceLastOrder', 'CashbackAmount', 'Churn'])


In [3]:
numerical_columns = [
    "Tenure",
    "WarehouseToHome",
    "NumberOfDeviceRegistered",
    "SatisfactionScore",
    "NumberOfAddress",
    "Complain",
    "DaySinceLastOrder",
    "CashbackAmount"
]
target_column = "Churn"

In [4]:
import numpy as np

In [5]:
print("Columns:")
for column in transactions[0].keys():
    print(repr(column))

Columns:
'Tenure'
'WarehouseToHome'
'NumberOfDeviceRegistered'
'PreferedOrderCat'
'SatisfactionScore'
'MaritalStatus'
'NumberOfAddress'
'Complain'
'DaySinceLastOrder'
'CashbackAmount'
'Churn'


In [10]:
def transaction_clean(transactions):
    clean_transactions = []
    for row in transactions:
        valid = True
        for column in numerical_columns:
            if row[column].strip() == "":
                valid = False
                break
        if valid:
            clean_transactions.append(row)

    print("Original rows:", len(transactions))
    print("Clean rows:", len(clean_transactions))
    print("Removed rows:", len(transactions) - len(clean_transactions))
    return clean_transactions

In [12]:
X = np.array([
    [
        float(row[column])
        for column in numerical_columns
    ]
    for row in transaction_clean(transactions)
])

print("X shape:", X.shape)
print("X ndim:", X.ndim)
print("X size:", X.size)
print("X dtype:", X.dtype)

Original rows: 3365
Clean rows: 3365
Removed rows: 0
X shape: (3365, 8)
X ndim: 2
X size: 26920
X dtype: float64


In [14]:
y = np.array([
    int(row["Churn"])
    for row in transaction_clean(transactions)
])

print("y shape:", y.shape)
print("y ndim:", y.ndim)
print("y size:", y.size)
print("y dtype:", y.dtype)

Original rows: 3365
Clean rows: 3365
Removed rows: 0
y shape: (3365,)
y ndim: 1
y size: 3365
y dtype: int64


In [15]:
print(X[0])

[ 15.    29.     4.     3.     2.     0.     7.   143.32]


In [16]:
print(X[:5])

[[ 15.    29.     4.     3.     2.     0.     7.   143.32]
 [  7.    25.     4.     1.     2.     0.     7.   129.29]
 [ 27.    13.     3.     1.     5.     0.     7.   168.54]
 [ 30.    15.     4.     4.     8.     0.     8.   322.17]
 [  7.    16.     4.     2.     2.     0.    11.   152.81]]


In [18]:
print(X[0][:3])

[15. 29.  4.]
[15. 29.  4.]


In [19]:
print(X[-5:])

[[ 26.     7.     4.     1.     4.     0.     9.   295.99]
 [ 28.     9.     5.     3.     8.     0.     1.   231.86]
 [  8.     7.     2.     2.     4.     0.     4.   157.8 ]
 [ 30.     6.     5.     3.     3.     1.     2.   156.6 ]
 [  2.     7.     3.     5.     1.     0.     2.   153.73]]


In [24]:
print(X[:,0])
print(X[:][0])

[15.  7. 27. ...  8. 30.  2.]
[ 15.    29.     4.     3.     2.     0.     7.   143.32]


In [25]:
print(X[0,0])

15.0


In [26]:
print(X[0, 3])

3.0


In [27]:
print("First row:", X[0])
print("First 5 rows:\n", X[:5])
print("First 3 features of first customer:", X[0, :3])
print("Last 5 rows:\n", X[-5:])
print("Tenure column:\n", X[:, 0])
print("First customer's tenure:", X[0, 0])

First row: [ 15.    29.     4.     3.     2.     0.     7.   143.32]
First 5 rows:
 [[ 15.    29.     4.     3.     2.     0.     7.   143.32]
 [  7.    25.     4.     1.     2.     0.     7.   129.29]
 [ 27.    13.     3.     1.     5.     0.     7.   168.54]
 [ 30.    15.     4.     4.     8.     0.     8.   322.17]
 [  7.    16.     4.     2.     2.     0.    11.   152.81]]
First 3 features of first customer: [15. 29.  4.]
Last 5 rows:
 [[ 26.     7.     4.     1.     4.     0.     9.   295.99]
 [ 28.     9.     5.     3.     8.     0.     1.   231.86]
 [  8.     7.     2.     2.     4.     0.     4.   157.8 ]
 [ 30.     6.     5.     3.     3.     1.     2.   156.6 ]
 [  2.     7.     3.     5.     1.     0.     2.   153.73]]
Tenure column:
 [15.  7. 27. ...  8. 30.  2.]
First customer's tenure: 15.0


In [28]:
print("\nShapes:")
print("X:", X.shape)
print("X[0]:", X[0].shape)
print("X[:5]:", X[:5].shape)
print("X[0, :3]:", X[0, :3].shape)
print("X[:, 0]:", X[:, 0].shape)


Shapes:
X: (3365, 8)
X[0]: (8,)
X[:5]: (5, 8)
X[0, :3]: (3,)
X[:, 0]: (3365,)


In [30]:
tenure = X[:, 0]

print("Mean:", np.mean(tenure))
print("Median:", np.median(tenure))
print("Minimum:", np.min(tenure))
print("Maximum:", np.max(tenure))
print("Standard deviation:", np.std(tenure))

Mean: 10.177711738484398
Median: 9.0
Minimum: 0.0
Maximum: 61.0
Standard deviation: 8.51167764189064


In [34]:
means = np.mean(X, axis=0)
medians = np.median(X, axis=0)
minimums = np.min(X, axis=0)
maximums = np.max(X, axis=0)
stds = np.std(X, axis=0)

for i,column in enumerate(numerical_columns):
    print(
        column,
        "\n",
        "Mean:", means[i],
        "Median:", medians[i],
        "Min:", minimums[i],
        "Max:", maximums[i],
        "Std:", stds[i]
    )

Tenure 
 Mean: 10.177711738484398 Median: 9.0 Min: 0.0 Max: 61.0 Std: 8.511677641890593
WarehouseToHome 
 Mean: 15.713818722139672 Median: 14.0 Min: 5.0 Max: 127.0 Std: 8.512440113173325
NumberOfDeviceRegistered 
 Mean: 3.698959881129272 Median: 4.0 Min: 1.0 Max: 6.0 Std: 1.023940231989951
SatisfactionScore 
 Mean: 3.0942050520059436 Median: 3.0 Min: 1.0 Max: 5.0 Std: 1.380950530633791
NumberOfAddress 
 Mean: 4.296582466567608 Median: 3.0 Min: 1.0 Max: 22.0 Std: 2.62585219724433
Complain 
 Mean: 0.2835066864784547 Median: 0.0 Min: 0.0 Max: 1.0 Std: 0.4507001721770861
DaySinceLastOrder 
 Mean: 4.780089153046062 Median: 4.0 Min: 0.0 Max: 46.0 Std: 3.6852892561389807
CashbackAmount 
 Mean: 179.77472511144077 Median: 165.14 Min: 0.0 Max: 324.99 Std: 48.286295834016975


In [41]:
print("X shape:", X.shape)

print("\nColumn means:")
print(np.mean(X,axis=0))

print("\nColumn medians:")
print(np.median(X, axis=0))

print("\nColumn minimums:")
print(np.min(X, axis=0))

print("\nColumn maximums:")
print(np.max(X, axis=0))

print("\nColumn standard deviations:")
print(np.std(X, axis=0))

print("\nFirst 5 rows:")
print(X[:5])

print("\nFirst 5 row means:")
print(np.mean(X[:5], axis = 0))



X shape: (3365, 8)

Column means:
[ 10.17771174  15.71381872   3.69895988   3.09420505   4.29658247
   0.28350669   4.78008915 179.77472511]

Column medians:
[  9.    14.     4.     3.     3.     0.     4.   165.14]

Column minimums:
[0. 5. 1. 1. 1. 0. 0. 0.]

Column maximums:
[ 61.   127.     6.     5.    22.     1.    46.   324.99]

Column standard deviations:
[ 8.51167764  8.51244011  1.02394023  1.38095053  2.6258522   0.45070017
  3.68528926 48.28629583]

First 5 rows:
[[ 15.    29.     4.     3.     2.     0.     7.   143.32]
 [  7.    25.     4.     1.     2.     0.     7.   129.29]
 [ 27.    13.     3.     1.     5.     0.     7.   168.54]
 [ 30.    15.     4.     4.     8.     0.     8.   322.17]
 [  7.    16.     4.     2.     2.     0.    11.   152.81]]

First 5 row means:
[ 17.2    19.6     3.8     2.2     3.8     0.      8.    183.226]


In [46]:
satisfaction = X[:,3]
low_satisfaction = satisfaction <= 2
print(low_satisfaction)
print("low_satisfaction Count:", np.sum(low_satisfaction))

[False  True  True ...  True False False]
low_satisfaction Count: 1014


In [48]:
complain = X[:,5]
mask = (satisfaction<=2) & (complain == 1)
result = X[mask]
print("Matching customers:", len(result))

Matching customers: 324


In [52]:
mask1 = X[:,0]>10
mask2 = X[:,7]>300
mask3 = (X[:,3]<=2) & (X[:,5] == 1)
print("Tenure > 10:", np.sum(mask1))
print("Cashback > 300:", np.sum(mask2))
print("Low satisfaction + complaint:", np.sum(mask3))

Tenure > 10: 1423
Cashback > 300: 100
Low satisfaction + complaint: 324


In [53]:
low_satisfaction_flag = np.where(low_satisfaction <= 2 , 1 , 0)
print(low_satisfaction_flag)

[1 1 1 ... 1 1 1]


In [56]:
days_since_order = X[:, 6]
customer_inactive_flag = np.where(days_since_order > 10, 1, 0)
print(customer_inactive_flag)

[0 0 0 ... 0 0 0]


In [57]:
complain = X[:, 5]

complaint_flag = np.where(complain == 1, 1, 0)

print(complaint_flag)

[0 0 0 ... 0 1 0]


In [59]:

print("Low satisfaction:", np.sum(low_satisfaction_flag))
print("Inactive:", np.sum(customer_inactive_flag))
print("Complaints:", np.sum(complaint_flag))

Low satisfaction: 3365
Inactive: 201
Complaints: 954


In [61]:
tenure = X[:, 0]
devices = X[:, 2]
addresses = X[:, 4]
days_since_order = X[:, 6]

engagement_score = (
    tenure+devices+addresses-days_since_order)

print(engagement_score)

[14.  6. 28. ... 10. 36.  4.]


In [64]:
cashback_per_tenure = np.where(
    tenure != 0,
    cashback / tenure,
    0
)

print(cashback_per_tenure[:10])

[  9.55466667  18.47         6.24222222  10.739       21.83
 149.51       154.73        12.45636364   9.26058824  11.27375   ]


C:\Users\Aayus\AppData\Local\Temp\ipykernel_20880\2914578446.py:3: RuntimeWarning: divide by zero encountered in divide
  cashback / tenure,
